[features]
seeds = false
skip-lint = false

[programs.localnet]
seekalpha = "4occZKXYz3tXjNQYr58YhAwWsCKsP2yZaYdSgQtgMY3a"

[programs.devnet]
seekalpha = "4occZKXYz3tXjNQYr58YhAwWsCKsP2yZaYdSgQtgMY3a"

[programs.mainnet]
seekalpha = "4occZKXYz3tXjNQYr58YhAwWsCKsP2yZaYdSgQtgMY3a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
